name: Message Validating Client and Server Test

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test Run
      run: |
        cd Message\ Validating\ Client\ and\ Server 
        sudo python3 server.py 7894 Message_File_Students/Advanced-message/key.txt & sudo python3 client.py localhost 7894 Message_File_Students/Advanced-message/message3.txt Message_File_Students/Advanced-message/signature3.txt
