name: Web Server Characterization Test

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install scapy
    - name: Test Run
      run: |
        cd Web\ Server\ Characterization/ 
        python3 measure-webserver.py pcap1.pcap 93.184.216.34 80
