name: Web Server Characterization Test

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.1
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install scapy
    - name: pcap1 Test
      run: |
        cd Web\ Server\ Characterization/ 
        python3 measure-webserver.py pcap1.pcap 93.184.216.34 80
    - name: pcap2 Test
      run: |
        cd Web\ Server\ Characterization/
        python3 measure-webserver.py pcap2.pcap 93.184.216.34 80
        python3 measure-webserver.py pcap2.pcap 17.253.144.10 80
    - name: pcap3 Test
      run: |
        cd Web\ Server\ Characterization/
        python3 measure-webserver.py pcap3.pcap 188.184.100.182 80
        python3 measure-webserver.py pcap3.pcap 34.223.124.45 80